env: flex
runtime: php
runtime_config:
  document_root: ./www

beta_settings:
    cloud_sql_instances: 'projeto-gdoks:southamerica-east1:mysql-gdoks'

handlers:
- url: /api/(.*)
  script: ./www/api/index.php