insert into gdoks_subareas (nome, codigo, id_area) values ('Garrison-378', 'GAR425', 174);
insert into gdoks_subareas (nome, codigo, id_area) values ('Luster-728', 'LUS450', 31);
insert into gdoks_subareas (nome, codigo, id_area) values ('Reindahl-174', 'REI147', 57);
insert into gdoks_subareas (nome, codigo, id_area) values ('Clove-721', 'CLO174', 14);
insert into gdoks_subareas (nome, codigo, id_area) values ('Mendota-727', 'MEN306', 165);
insert into gdoks_subareas (nome, codigo, id_area) values ('Shasta-978', 'SHA982', 158);
insert into gdoks_subareas (nome, codigo, id_area) values ('Johnson-982', 'JOH378', 154);
insert into gdoks_subareas (nome, codigo, id_area) values ('Pennsylvania-676', 'PEN359', 141);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hanson-229', 'HAN462', 176);
insert into gdoks_subareas (nome, codigo, id_area) values ('Crest Line-258', 'CRE310', 121);
insert into gdoks_subareas (nome, codigo, id_area) values ('Autumn Leaf-942', 'AUT584', 15);
insert into gdoks_subareas (nome, codigo, id_area) values ('Fremont-279', 'FRE805', 122);
insert into gdoks_subareas (nome, codigo, id_area) values ('Sauthoff-656', 'SAU757', 10);
insert into gdoks_subareas (nome, codigo, id_area) values ('Norway Maple-192', 'NOR237', 77);
insert into gdoks_subareas (nome, codigo, id_area) values ('Northridge-384', 'NOR286', 109);
insert into gdoks_subareas (nome, codigo, id_area) values ('Holmberg-136', 'HOL896', 48);
insert into gdoks_subareas (nome, codigo, id_area) values ('Bobwhite-309', 'BOB448', 69);
insert into gdoks_subareas (nome, codigo, id_area) values ('Mendota-457', 'MEN125', 8);
insert into gdoks_subareas (nome, codigo, id_area) values ('Monument-969', 'MON639', 38);
insert into gdoks_subareas (nome, codigo, id_area) values ('Reinke-464', 'REI523', 174);
insert into gdoks_subareas (nome, codigo, id_area) values ('Kropf-221', 'KRO909', 105);
insert into gdoks_subareas (nome, codigo, id_area) values ('Schmedeman-512', 'SCH885', 180);
insert into gdoks_subareas (nome, codigo, id_area) values ('Armistice-853', 'ARM438', 105);
insert into gdoks_subareas (nome, codigo, id_area) values ('Lakeland-401', 'LAK330', 156);
insert into gdoks_subareas (nome, codigo, id_area) values ('Mcguire-859', 'MCG670', 167);
insert into gdoks_subareas (nome, codigo, id_area) values ('Ridge Oak-809', 'RID785', 4);
insert into gdoks_subareas (nome, codigo, id_area) values ('Dakota-922', 'DAK225', 45);
insert into gdoks_subareas (nome, codigo, id_area) values ('Melvin-290', 'MEL299', 69);
insert into gdoks_subareas (nome, codigo, id_area) values ('Fordem-979', 'FOR852', 174);
insert into gdoks_subareas (nome, codigo, id_area) values ('Thierer-493', 'THI783', 44);
insert into gdoks_subareas (nome, codigo, id_area) values ('Park Meadow-681', 'PAR892', 102);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hallows-575', 'HAL493', 135);
insert into gdoks_subareas (nome, codigo, id_area) values ('Gina-718', 'GIN986', 78);
insert into gdoks_subareas (nome, codigo, id_area) values ('Sloan-196', 'SLO148', 139);
insert into gdoks_subareas (nome, codigo, id_area) values ('Glacier Hill-936', 'GLA690', 30);
insert into gdoks_subareas (nome, codigo, id_area) values ('Thompson-571', 'THO982', 47);
insert into gdoks_subareas (nome, codigo, id_area) values ('Dakota-802', 'DAK490', 131);
insert into gdoks_subareas (nome, codigo, id_area) values ('Marcy-299', 'MAR565', 2);
insert into gdoks_subareas (nome, codigo, id_area) values ('Shopko-388', 'SHO727', 57);
insert into gdoks_subareas (nome, codigo, id_area) values ('Warrior-527', 'WAR664', 15);
insert into gdoks_subareas (nome, codigo, id_area) values ('Dapin-758', 'DAP653', 85);
insert into gdoks_subareas (nome, codigo, id_area) values ('Bay-283', 'BAY576', 118);
insert into gdoks_subareas (nome, codigo, id_area) values ('Ronald Regan-374', 'RON322', 85);
insert into gdoks_subareas (nome, codigo, id_area) values ('Jenna-502', 'JEN804', 92);
insert into gdoks_subareas (nome, codigo, id_area) values ('Reinke-689', 'REI601', 128);
insert into gdoks_subareas (nome, codigo, id_area) values ('Oakridge-172', 'OAK641', 13);
insert into gdoks_subareas (nome, codigo, id_area) values ('Linden-824', 'LIN952', 6);
insert into gdoks_subareas (nome, codigo, id_area) values ('Kropf-615', 'KRO402', 117);
insert into gdoks_subareas (nome, codigo, id_area) values ('Carioca-131', 'CAR531', 124);
insert into gdoks_subareas (nome, codigo, id_area) values ('Leroy-162', 'LER937', 25);
insert into gdoks_subareas (nome, codigo, id_area) values ('Bartelt-571', 'BAR243', 55);
insert into gdoks_subareas (nome, codigo, id_area) values ('Montana-238', 'MON633', 11);
insert into gdoks_subareas (nome, codigo, id_area) values ('Reindahl-241', 'REI503', 18);
insert into gdoks_subareas (nome, codigo, id_area) values ('Southridge-714', 'SOU260', 162);
insert into gdoks_subareas (nome, codigo, id_area) values ('Forest-490', 'FOR728', 39);
insert into gdoks_subareas (nome, codigo, id_area) values ('Arapahoe-991', 'ARA669', 24);
insert into gdoks_subareas (nome, codigo, id_area) values ('Graceland-426', 'GRA468', 33);
insert into gdoks_subareas (nome, codigo, id_area) values ('Shopko-344', 'SHO350', 84);
insert into gdoks_subareas (nome, codigo, id_area) values ('Memorial-577', 'MEM973', 164);
insert into gdoks_subareas (nome, codigo, id_area) values ('Warner-959', 'WAR918', 29);
insert into gdoks_subareas (nome, codigo, id_area) values ('Manley-639', 'MAN184', 44);
insert into gdoks_subareas (nome, codigo, id_area) values ('Birchwood-836', 'BIR899', 50);
insert into gdoks_subareas (nome, codigo, id_area) values ('Pleasure-883', 'PLE209', 55);
insert into gdoks_subareas (nome, codigo, id_area) values ('Village Green-833', 'VIL376', 148);
insert into gdoks_subareas (nome, codigo, id_area) values ('Lakeland-243', 'LAK596', 77);
insert into gdoks_subareas (nome, codigo, id_area) values ('Ruskin-174', 'RUS395', 72);
insert into gdoks_subareas (nome, codigo, id_area) values ('Artisan-980', 'ART177', 128);
insert into gdoks_subareas (nome, codigo, id_area) values ('Sage-992', 'SAG369', 5);
insert into gdoks_subareas (nome, codigo, id_area) values ('Macpherson-242', 'MAC151', 74);
insert into gdoks_subareas (nome, codigo, id_area) values ('Golf-581', 'GOL394', 85);
insert into gdoks_subareas (nome, codigo, id_area) values ('Charing Cross-620', 'CHA990', 163);
insert into gdoks_subareas (nome, codigo, id_area) values ('Colorado-835', 'COL583', 137);
insert into gdoks_subareas (nome, codigo, id_area) values ('Shopko-546', 'SHO517', 61);
insert into gdoks_subareas (nome, codigo, id_area) values ('Dayton-250', 'DAY813', 128);
insert into gdoks_subareas (nome, codigo, id_area) values ('Eagle Crest-224', 'EAG810', 96);
insert into gdoks_subareas (nome, codigo, id_area) values ('Nevada-384', 'NEV266', 176);
insert into gdoks_subareas (nome, codigo, id_area) values ('Farmco-429', 'FAR325', 132);
insert into gdoks_subareas (nome, codigo, id_area) values ('Sloan-171', 'SLO403', 138);
insert into gdoks_subareas (nome, codigo, id_area) values ('Drewry-817', 'DRE131', 120);
insert into gdoks_subareas (nome, codigo, id_area) values ('Mallory-682', 'MAL942', 89);
insert into gdoks_subareas (nome, codigo, id_area) values ('Algoma-762', 'ALG504', 2);
insert into gdoks_subareas (nome, codigo, id_area) values ('Crest Line-880', 'CRE378', 45);
insert into gdoks_subareas (nome, codigo, id_area) values ('Cody-203', 'COD744', 150);
insert into gdoks_subareas (nome, codigo, id_area) values ('Summerview-930', 'SUM511', 44);
insert into gdoks_subareas (nome, codigo, id_area) values ('Portage-509', 'POR931', 146);
insert into gdoks_subareas (nome, codigo, id_area) values ('Golf-692', 'GOL250', 108);
insert into gdoks_subareas (nome, codigo, id_area) values ('Ilene-361', 'ILE662', 26);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hoepker-579', 'HOE436', 174);
insert into gdoks_subareas (nome, codigo, id_area) values ('Fallview-488', 'FAL523', 43);
insert into gdoks_subareas (nome, codigo, id_area) values ('Steensland-969', 'STE723', 80);
insert into gdoks_subareas (nome, codigo, id_area) values ('Iowa-241', 'IOW106', 16);
insert into gdoks_subareas (nome, codigo, id_area) values ('Lakewood Gardens-870', 'LAK905', 1);
insert into gdoks_subareas (nome, codigo, id_area) values ('Barby-496', 'BAR319', 29);
insert into gdoks_subareas (nome, codigo, id_area) values ('Commercial-200', 'COM977', 105);
insert into gdoks_subareas (nome, codigo, id_area) values ('Cottonwood-788', 'COT153', 57);
insert into gdoks_subareas (nome, codigo, id_area) values ('Muir-164', 'MUI932', 80);
insert into gdoks_subareas (nome, codigo, id_area) values ('Kedzie-122', 'KED797', 162);
insert into gdoks_subareas (nome, codigo, id_area) values ('Sycamore-939', 'SYC571', 122);
insert into gdoks_subareas (nome, codigo, id_area) values ('Monica-737', 'MON877', 75);
insert into gdoks_subareas (nome, codigo, id_area) values ('Stuart-436', 'STU863', 35);
insert into gdoks_subareas (nome, codigo, id_area) values ('Lawn-516', 'LAW935', 47);
insert into gdoks_subareas (nome, codigo, id_area) values ('Lotheville-469', 'LOT496', 111);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hallows-373', 'HAL479', 161);
insert into gdoks_subareas (nome, codigo, id_area) values ('Sunnyside-314', 'SUN358', 78);
insert into gdoks_subareas (nome, codigo, id_area) values ('Green Ridge-985', 'GRE343', 103);
insert into gdoks_subareas (nome, codigo, id_area) values ('Aberg-456', 'ABE869', 34);
insert into gdoks_subareas (nome, codigo, id_area) values ('Center-159', 'CEN764', 83);
insert into gdoks_subareas (nome, codigo, id_area) values ('Sachtjen-680', 'SAC651', 135);
insert into gdoks_subareas (nome, codigo, id_area) values ('Oriole-591', 'ORI852', 39);
insert into gdoks_subareas (nome, codigo, id_area) values ('Manley-500', 'MAN466', 33);
insert into gdoks_subareas (nome, codigo, id_area) values ('Clarendon-973', 'CLA715', 23);
insert into gdoks_subareas (nome, codigo, id_area) values ('Pond-678', 'PON219', 160);
insert into gdoks_subareas (nome, codigo, id_area) values ('Oneill-590', 'ONE939', 58);
insert into gdoks_subareas (nome, codigo, id_area) values ('Jenifer-567', 'JEN432', 177);
insert into gdoks_subareas (nome, codigo, id_area) values ('Fieldstone-436', 'FIE891', 172);
insert into gdoks_subareas (nome, codigo, id_area) values ('Tennessee-611', 'TEN735', 66);
insert into gdoks_subareas (nome, codigo, id_area) values ('Novick-257', 'NOV657', 11);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hoffman-147', 'HOF505', 2);
insert into gdoks_subareas (nome, codigo, id_area) values ('Northview-119', 'NOR426', 139);
insert into gdoks_subareas (nome, codigo, id_area) values ('Mifflin-241', 'MIF469', 131);
insert into gdoks_subareas (nome, codigo, id_area) values ('Brown-887', 'BRO635', 48);
insert into gdoks_subareas (nome, codigo, id_area) values ('Huxley-737', 'HUX574', 53);
insert into gdoks_subareas (nome, codigo, id_area) values ('Dakota-135', 'DAK468', 64);
insert into gdoks_subareas (nome, codigo, id_area) values ('Towne-368', 'TOW725', 165);
insert into gdoks_subareas (nome, codigo, id_area) values ('Esch-126', 'ESC495', 83);
insert into gdoks_subareas (nome, codigo, id_area) values ('Daystar-570', 'DAY910', 121);
insert into gdoks_subareas (nome, codigo, id_area) values ('Glacier Hill-933', 'GLA108', 178);
insert into gdoks_subareas (nome, codigo, id_area) values ('Stephen-507', 'STE499', 127);
insert into gdoks_subareas (nome, codigo, id_area) values ('Granby-612', 'GRA445', 96);
insert into gdoks_subareas (nome, codigo, id_area) values ('Loomis-254', 'LOO485', 64);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hansons-750', 'HAN877', 36);
insert into gdoks_subareas (nome, codigo, id_area) values ('Basil-569', 'BAS110', 104);
insert into gdoks_subareas (nome, codigo, id_area) values ('Cardinal-384', 'CAR934', 20);
insert into gdoks_subareas (nome, codigo, id_area) values ('International-317', 'INT659', 89);
insert into gdoks_subareas (nome, codigo, id_area) values ('John Wall-270', 'JOH119', 171);
insert into gdoks_subareas (nome, codigo, id_area) values ('Forster-690', 'FOR707', 130);
insert into gdoks_subareas (nome, codigo, id_area) values ('Elgar-344', 'ELG662', 127);
insert into gdoks_subareas (nome, codigo, id_area) values ('Tomscot-875', 'TOM782', 115);
insert into gdoks_subareas (nome, codigo, id_area) values ('Charing Cross-966', 'CHA800', 132);
insert into gdoks_subareas (nome, codigo, id_area) values ('Sundown-106', 'SUN124', 97);
insert into gdoks_subareas (nome, codigo, id_area) values ('Iowa-673', 'IOW226', 88);
insert into gdoks_subareas (nome, codigo, id_area) values ('Sutteridge-699', 'SUT910', 29);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hoard-951', 'HOA802', 133);
insert into gdoks_subareas (nome, codigo, id_area) values ('School-743', 'SCH705', 119);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hoepker-272', 'HOE296', 61);
insert into gdoks_subareas (nome, codigo, id_area) values ('Beilfuss-383', 'BEI629', 150);
insert into gdoks_subareas (nome, codigo, id_area) values ('Del Sol-799', 'DEL579', 10);
insert into gdoks_subareas (nome, codigo, id_area) values ('Burning Wood-804', 'BUR712', 169);
insert into gdoks_subareas (nome, codigo, id_area) values ('Meadow Vale-963', 'MEA778', 104);
insert into gdoks_subareas (nome, codigo, id_area) values ('Marcy-159', 'MAR396', 47);
insert into gdoks_subareas (nome, codigo, id_area) values ('Canary-355', 'CAN279', 62);
insert into gdoks_subareas (nome, codigo, id_area) values ('Independence-575', 'IND281', 61);
insert into gdoks_subareas (nome, codigo, id_area) values ('Crownhardt-528', 'CRO255', 36);
insert into gdoks_subareas (nome, codigo, id_area) values ('Carberry-638', 'CAR395', 39);
insert into gdoks_subareas (nome, codigo, id_area) values ('Amoth-543', 'AMO745', 153);
insert into gdoks_subareas (nome, codigo, id_area) values ('Autumn Leaf-615', 'AUT585', 165);
insert into gdoks_subareas (nome, codigo, id_area) values ('Nelson-518', 'NEL606', 70);
insert into gdoks_subareas (nome, codigo, id_area) values ('Gina-804', 'GIN608', 150);
insert into gdoks_subareas (nome, codigo, id_area) values ('Clyde Gallagher-960', 'CLY170', 59);
insert into gdoks_subareas (nome, codigo, id_area) values ('Dottie-642', 'DOT234', 17);
insert into gdoks_subareas (nome, codigo, id_area) values ('Mitchell-560', 'MIT215', 130);
insert into gdoks_subareas (nome, codigo, id_area) values ('Graceland-463', 'GRA802', 78);
insert into gdoks_subareas (nome, codigo, id_area) values ('Waubesa-931', 'WAU832', 38);
insert into gdoks_subareas (nome, codigo, id_area) values ('Mandrake-623', 'MAN633', 18);
insert into gdoks_subareas (nome, codigo, id_area) values ('Iowa-272', 'IOW956', 168);
insert into gdoks_subareas (nome, codigo, id_area) values ('Stone Corner-735', 'STO495', 2);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hooker-263', 'HOO961', 120);
insert into gdoks_subareas (nome, codigo, id_area) values ('Fremont-282', 'FRE289', 134);
insert into gdoks_subareas (nome, codigo, id_area) values ('Morning-939', 'MOR497', 160);
insert into gdoks_subareas (nome, codigo, id_area) values ('Straubel-486', 'STR504', 56);
insert into gdoks_subareas (nome, codigo, id_area) values ('Melody-325', 'MEL398', 8);
insert into gdoks_subareas (nome, codigo, id_area) values ('Ridgeview-448', 'RID997', 14);
insert into gdoks_subareas (nome, codigo, id_area) values ('Coolidge-280', 'COO516', 105);
insert into gdoks_subareas (nome, codigo, id_area) values ('Barby-970', 'BAR374', 178);
insert into gdoks_subareas (nome, codigo, id_area) values ('Trailsway-723', 'TRA642', 48);
insert into gdoks_subareas (nome, codigo, id_area) values ('Forest Dale-237', 'FOR897', 38);
insert into gdoks_subareas (nome, codigo, id_area) values ('Kingsford-550', 'KIN115', 50);
insert into gdoks_subareas (nome, codigo, id_area) values ('Sunnyside-572', 'SUN562', 140);
insert into gdoks_subareas (nome, codigo, id_area) values ('Tomscot-420', 'TOM739', 103);
insert into gdoks_subareas (nome, codigo, id_area) values ('Monterey-145', 'MON408', 81);
insert into gdoks_subareas (nome, codigo, id_area) values ('Schurz-799', 'SCH946', 51);
insert into gdoks_subareas (nome, codigo, id_area) values ('Crownhardt-596', 'CRO332', 178);
insert into gdoks_subareas (nome, codigo, id_area) values ('2nd-502', '2ND858', 12);
insert into gdoks_subareas (nome, codigo, id_area) values ('Ronald Regan-412', 'RON543', 115);
insert into gdoks_subareas (nome, codigo, id_area) values ('Grover-504', 'GRO209', 35);
insert into gdoks_subareas (nome, codigo, id_area) values ('Main-944', 'MAI374', 22);
insert into gdoks_subareas (nome, codigo, id_area) values ('Cambridge-513', 'CAM724', 17);
insert into gdoks_subareas (nome, codigo, id_area) values ('Iowa-344', 'IOW748', 83);
insert into gdoks_subareas (nome, codigo, id_area) values ('Vidon-724', 'VID168', 179);
insert into gdoks_subareas (nome, codigo, id_area) values ('Haas-300', 'HAA225', 125);
insert into gdoks_subareas (nome, codigo, id_area) values ('Morning-568', 'MOR161', 15);
insert into gdoks_subareas (nome, codigo, id_area) values ('Dakota-735', 'DAK108', 104);
insert into gdoks_subareas (nome, codigo, id_area) values ('Mandrake-473', 'MAN718', 106);
insert into gdoks_subareas (nome, codigo, id_area) values ('Spohn-304', 'SPO516', 117);
insert into gdoks_subareas (nome, codigo, id_area) values ('Warner-396', 'WAR277', 72);
insert into gdoks_subareas (nome, codigo, id_area) values ('Longview-781', 'LON318', 65);
insert into gdoks_subareas (nome, codigo, id_area) values ('Lien-761', 'LIE984', 8);
insert into gdoks_subareas (nome, codigo, id_area) values ('Stoughton-267', 'STO760', 172);
insert into gdoks_subareas (nome, codigo, id_area) values ('Katie-765', 'KAT925', 94);
insert into gdoks_subareas (nome, codigo, id_area) values ('Pankratz-635', 'PAN327', 87);
insert into gdoks_subareas (nome, codigo, id_area) values ('Roxbury-699', 'ROX457', 121);
insert into gdoks_subareas (nome, codigo, id_area) values ('Sachtjen-445', 'SAC523', 162);
insert into gdoks_subareas (nome, codigo, id_area) values ('Village Green-710', 'VIL527', 113);
insert into gdoks_subareas (nome, codigo, id_area) values ('Evergreen-898', 'EVE625', 133);
insert into gdoks_subareas (nome, codigo, id_area) values ('Arapahoe-239', 'ARA688', 174);
insert into gdoks_subareas (nome, codigo, id_area) values ('Bowman-845', 'BOW607', 100);
insert into gdoks_subareas (nome, codigo, id_area) values ('Buhler-836', 'BUH199', 104);
insert into gdoks_subareas (nome, codigo, id_area) values ('Clarendon-890', 'CLA390', 178);
insert into gdoks_subareas (nome, codigo, id_area) values ('Pine View-921', 'PIN364', 164);
insert into gdoks_subareas (nome, codigo, id_area) values ('Beilfuss-817', 'BEI303', 178);
insert into gdoks_subareas (nome, codigo, id_area) values ('Grasskamp-717', 'GRA401', 107);
insert into gdoks_subareas (nome, codigo, id_area) values ('Fisk-883', 'FIS343', 77);
insert into gdoks_subareas (nome, codigo, id_area) values ('Graceland-302', 'GRA916', 130);
insert into gdoks_subareas (nome, codigo, id_area) values ('Division-617', 'DIV720', 81);
insert into gdoks_subareas (nome, codigo, id_area) values ('Tony-274', 'TON340', 20);
insert into gdoks_subareas (nome, codigo, id_area) values ('Burrows-314', 'BUR827', 143);
insert into gdoks_subareas (nome, codigo, id_area) values ('Knutson-832', 'KNU491', 163);
insert into gdoks_subareas (nome, codigo, id_area) values ('Petterle-229', 'PET167', 163);
insert into gdoks_subareas (nome, codigo, id_area) values ('Marquette-899', 'MAR549', 22);
insert into gdoks_subareas (nome, codigo, id_area) values ('Novick-780', 'NOV853', 8);
insert into gdoks_subareas (nome, codigo, id_area) values ('La Follette-218', 'LA 372', 111);
insert into gdoks_subareas (nome, codigo, id_area) values ('Esch-875', 'ESC285', 138);
insert into gdoks_subareas (nome, codigo, id_area) values ('Lerdahl-242', 'LER893', 45);
insert into gdoks_subareas (nome, codigo, id_area) values ('Ludington-823', 'LUD892', 148);
insert into gdoks_subareas (nome, codigo, id_area) values ('Kings-652', 'KIN847', 142);
insert into gdoks_subareas (nome, codigo, id_area) values ('Esker-459', 'ESK408', 100);
insert into gdoks_subareas (nome, codigo, id_area) values ('Stoughton-804', 'STO360', 143);
insert into gdoks_subareas (nome, codigo, id_area) values ('Arapahoe-612', 'ARA917', 161);
insert into gdoks_subareas (nome, codigo, id_area) values ('Dunning-158', 'DUN829', 177);
insert into gdoks_subareas (nome, codigo, id_area) values ('Washington-282', 'WAS942', 103);
insert into gdoks_subareas (nome, codigo, id_area) values ('Portage-788', 'POR939', 88);
insert into gdoks_subareas (nome, codigo, id_area) values ('Longview-231', 'LON376', 148);
insert into gdoks_subareas (nome, codigo, id_area) values ('Jackson-698', 'JAC810', 149);
insert into gdoks_subareas (nome, codigo, id_area) values ('Donald-258', 'DON954', 72);
insert into gdoks_subareas (nome, codigo, id_area) values ('Northwestern-883', 'NOR552', 155);
insert into gdoks_subareas (nome, codigo, id_area) values ('Stuart-695', 'STU755', 109);
insert into gdoks_subareas (nome, codigo, id_area) values ('Mcguire-801', 'MCG252', 179);
insert into gdoks_subareas (nome, codigo, id_area) values ('Mcguire-905', 'MCG773', 152);
insert into gdoks_subareas (nome, codigo, id_area) values ('Dottie-435', 'DOT768', 88);
insert into gdoks_subareas (nome, codigo, id_area) values ('Bonner-521', 'BON384', 158);
insert into gdoks_subareas (nome, codigo, id_area) values ('Gina-452', 'GIN114', 179);
insert into gdoks_subareas (nome, codigo, id_area) values ('Browning-927', 'BRO391', 3);
insert into gdoks_subareas (nome, codigo, id_area) values ('Village-495', 'VIL541', 141);
insert into gdoks_subareas (nome, codigo, id_area) values ('Butternut-834', 'BUT485', 10);
insert into gdoks_subareas (nome, codigo, id_area) values ('Russell-948', 'RUS720', 147);
insert into gdoks_subareas (nome, codigo, id_area) values ('Forest Run-688', 'FOR730', 47);
insert into gdoks_subareas (nome, codigo, id_area) values ('Mendota-650', 'MEN212', 47);
insert into gdoks_subareas (nome, codigo, id_area) values ('Russell-465', 'RUS227', 59);
insert into gdoks_subareas (nome, codigo, id_area) values ('Golf-640', 'GOL703', 149);
insert into gdoks_subareas (nome, codigo, id_area) values ('Prentice-356', 'PRE742', 42);
insert into gdoks_subareas (nome, codigo, id_area) values ('Scoville-537', 'SCO774', 51);
insert into gdoks_subareas (nome, codigo, id_area) values ('Burrows-359', 'BUR631', 119);
insert into gdoks_subareas (nome, codigo, id_area) values ('Lotheville-652', 'LOT679', 48);
insert into gdoks_subareas (nome, codigo, id_area) values ('Corry-186', 'COR831', 76);
insert into gdoks_subareas (nome, codigo, id_area) values ('Wayridge-987', 'WAY156', 139);
insert into gdoks_subareas (nome, codigo, id_area) values ('La Follette-574', 'LA 459', 95);
insert into gdoks_subareas (nome, codigo, id_area) values ('Chive-576', 'CHI454', 46);
insert into gdoks_subareas (nome, codigo, id_area) values ('Scott-734', 'SCO627', 141);
insert into gdoks_subareas (nome, codigo, id_area) values ('Brentwood-234', 'BRE722', 47);
insert into gdoks_subareas (nome, codigo, id_area) values ('Kennedy-828', 'KEN447', 155);
insert into gdoks_subareas (nome, codigo, id_area) values ('Lotheville-859', 'LOT227', 158);
insert into gdoks_subareas (nome, codigo, id_area) values ('Marquette-284', 'MAR196', 155);
insert into gdoks_subareas (nome, codigo, id_area) values ('Reindahl-433', 'REI976', 156);
insert into gdoks_subareas (nome, codigo, id_area) values ('Doe Crossing-674', 'DOE947', 116);
insert into gdoks_subareas (nome, codigo, id_area) values ('Carioca-885', 'CAR871', 14);
insert into gdoks_subareas (nome, codigo, id_area) values ('Sullivan-114', 'SUL105', 133);
insert into gdoks_subareas (nome, codigo, id_area) values ('Clove-550', 'CLO308', 83);
insert into gdoks_subareas (nome, codigo, id_area) values ('Kingsford-161', 'KIN499', 118);
insert into gdoks_subareas (nome, codigo, id_area) values ('Veith-138', 'VEI981', 25);
insert into gdoks_subareas (nome, codigo, id_area) values ('Dovetail-201', 'DOV322', 64);
insert into gdoks_subareas (nome, codigo, id_area) values ('John Wall-443', 'JOH219', 61);
insert into gdoks_subareas (nome, codigo, id_area) values ('Granby-889', 'GRA902', 105);
insert into gdoks_subareas (nome, codigo, id_area) values ('Heffernan-173', 'HEF348', 169);
insert into gdoks_subareas (nome, codigo, id_area) values ('Fremont-945', 'FRE990', 143);
insert into gdoks_subareas (nome, codigo, id_area) values ('Anderson-170', 'AND449', 170);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hooker-598', 'HOO453', 2);
insert into gdoks_subareas (nome, codigo, id_area) values ('Paget-979', 'PAG502', 86);
insert into gdoks_subareas (nome, codigo, id_area) values ('Brickson Park-951', 'BRI975', 109);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hovde-143', 'HOV725', 15);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hollow Ridge-780', 'HOL944', 178);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hagan-652', 'HAG830', 37);
insert into gdoks_subareas (nome, codigo, id_area) values ('Esker-550', 'ESK727', 61);
insert into gdoks_subareas (nome, codigo, id_area) values ('Roxbury-613', 'ROX628', 157);
insert into gdoks_subareas (nome, codigo, id_area) values ('Mandrake-922', 'MAN739', 88);
insert into gdoks_subareas (nome, codigo, id_area) values ('Bonner-707', 'BON795', 35);
insert into gdoks_subareas (nome, codigo, id_area) values ('Longview-247', 'LON592', 180);
insert into gdoks_subareas (nome, codigo, id_area) values ('Stuart-403', 'STU940', 111);
insert into gdoks_subareas (nome, codigo, id_area) values ('Boyd-533', 'BOY940', 128);
insert into gdoks_subareas (nome, codigo, id_area) values ('Golf Course-805', 'GOL273', 48);
insert into gdoks_subareas (nome, codigo, id_area) values ('Vera-958', 'VER187', 151);
insert into gdoks_subareas (nome, codigo, id_area) values ('Dennis-789', 'DEN100', 8);
insert into gdoks_subareas (nome, codigo, id_area) values ('Canary-217', 'CAN260', 24);
insert into gdoks_subareas (nome, codigo, id_area) values ('Kings-166', 'KIN546', 72);
insert into gdoks_subareas (nome, codigo, id_area) values ('Charing Cross-771', 'CHA760', 179);
insert into gdoks_subareas (nome, codigo, id_area) values ('Mosinee-885', 'MOS336', 157);
insert into gdoks_subareas (nome, codigo, id_area) values ('Del Mar-773', 'DEL880', 97);
insert into gdoks_subareas (nome, codigo, id_area) values ('Maple Wood-309', 'MAP810', 147);
insert into gdoks_subareas (nome, codigo, id_area) values ('Garrison-379', 'GAR359', 150);
insert into gdoks_subareas (nome, codigo, id_area) values ('Norway Maple-671', 'NOR282', 130);
insert into gdoks_subareas (nome, codigo, id_area) values ('Dwight-959', 'DWI295', 29);
insert into gdoks_subareas (nome, codigo, id_area) values ('Dawn-629', 'DAW299', 131);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hovde-161', 'HOV358', 33);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hallows-295', 'HAL791', 26);
insert into gdoks_subareas (nome, codigo, id_area) values ('Killdeer-374', 'KIL181', 105);
insert into gdoks_subareas (nome, codigo, id_area) values ('Blue Bill Park-126', 'BLU997', 143);
insert into gdoks_subareas (nome, codigo, id_area) values ('Helena-699', 'HEL857', 2);
insert into gdoks_subareas (nome, codigo, id_area) values ('5th-545', '5TH546', 11);
insert into gdoks_subareas (nome, codigo, id_area) values ('Susan-143', 'SUS542', 18);
insert into gdoks_subareas (nome, codigo, id_area) values ('Forster-160', 'FOR101', 151);
insert into gdoks_subareas (nome, codigo, id_area) values ('Alpine-629', 'ALP260', 40);
insert into gdoks_subareas (nome, codigo, id_area) values ('Kim-764', 'KIM435', 126);
insert into gdoks_subareas (nome, codigo, id_area) values ('Shopko-374', 'SHO793', 41);
insert into gdoks_subareas (nome, codigo, id_area) values ('Grover-456', 'GRO198', 171);
insert into gdoks_subareas (nome, codigo, id_area) values ('Mosinee-765', 'MOS960', 15);
insert into gdoks_subareas (nome, codigo, id_area) values ('Homewood-660', 'HOM520', 107);
insert into gdoks_subareas (nome, codigo, id_area) values ('Bowman-716', 'BOW109', 145);
insert into gdoks_subareas (nome, codigo, id_area) values ('Pond-370', 'PON263', 106);
insert into gdoks_subareas (nome, codigo, id_area) values ('Grasskamp-349', 'GRA503', 32);
insert into gdoks_subareas (nome, codigo, id_area) values ('Warbler-154', 'WAR936', 12);
insert into gdoks_subareas (nome, codigo, id_area) values ('Kim-404', 'KIM707', 163);
insert into gdoks_subareas (nome, codigo, id_area) values ('Bluejay-147', 'BLU698', 89);
insert into gdoks_subareas (nome, codigo, id_area) values ('Melby-928', 'MEL607', 102);
insert into gdoks_subareas (nome, codigo, id_area) values ('Rutledge-851', 'RUT995', 101);
insert into gdoks_subareas (nome, codigo, id_area) values ('Fuller-432', 'FUL700', 2);
insert into gdoks_subareas (nome, codigo, id_area) values ('Hazelcrest-845', 'HAZ214', 168);
insert into gdoks_subareas (nome, codigo, id_area) values ('Spenser-912', 'SPE451', 143);
insert into gdoks_subareas (nome, codigo, id_area) values ('Larry-185', 'LAR629', 132);
insert into gdoks_subareas (nome, codigo, id_area) values ('Warrior-122', 'WAR815', 23);
insert into gdoks_subareas (nome, codigo, id_area) values ('Killdeer-260', 'KIL582', 148);
insert into gdoks_subareas (nome, codigo, id_area) values ('Carey-237', 'CAR831', 71);
insert into gdoks_subareas (nome, codigo, id_area) values ('Bashford-379', 'BAS685', 160);
insert into gdoks_subareas (nome, codigo, id_area) values ('Sycamore-961', 'SYC524', 16);
insert into gdoks_subareas (nome, codigo, id_area) values ('Canary-984', 'CAN474', 139);
insert into gdoks_subareas (nome, codigo, id_area) values ('Vidon-326', 'VID129', 179);
insert into gdoks_subareas (nome, codigo, id_area) values ('Bluestem-751', 'BLU139', 43);
insert into gdoks_subareas (nome, codigo, id_area) values ('Drewry-989', 'DRE695', 116);
insert into gdoks_subareas (nome, codigo, id_area) values ('Green Ridge-937', 'GRE491', 119);
insert into gdoks_subareas (nome, codigo, id_area) values ('Badeau-225', 'BAD491', 110);
insert into gdoks_subareas (nome, codigo, id_area) values ('Kim-148', 'KIM939', 39);
insert into gdoks_subareas (nome, codigo, id_area) values ('Lake View-509', 'LAK731', 26);
insert into gdoks_subareas (nome, codigo, id_area) values ('Riverside-536', 'RIV872', 46);
insert into gdoks_subareas (nome, codigo, id_area) values ('Cambridge-608', 'CAM209', 55);
insert into gdoks_subareas (nome, codigo, id_area) values ('Anniversary-223', 'ANN628', 149);
insert into gdoks_subareas (nome, codigo, id_area) values ('Luster-701', 'LUS177', 125);
insert into gdoks_subareas (nome, codigo, id_area) values ('Norway Maple-867', 'NOR395', 127);
insert into gdoks_subareas (nome, codigo, id_area) values ('Moland-179', 'MOL575', 146);
insert into gdoks_subareas (nome, codigo, id_area) values ('La Follette-122', 'LA 376', 173);
insert into gdoks_subareas (nome, codigo, id_area) values ('Fisk-305', 'FIS771', 149);
insert into gdoks_subareas (nome, codigo, id_area) values ('Tony-226', 'TON318', 99);
insert into gdoks_subareas (nome, codigo, id_area) values ('Old Shore-740', 'OLD222', 119);
insert into gdoks_subareas (nome, codigo, id_area) values ('Fair Oaks-782', 'FAI203', 93);
insert into gdoks_subareas (nome, codigo, id_area) values ('Carioca-979', 'CAR345', 111);
insert into gdoks_subareas (nome, codigo, id_area) values ('Delaware-754', 'DEL831', 121);
insert into gdoks_subareas (nome, codigo, id_area) values ('Kings-307', 'KIN169', 8);
insert into gdoks_subareas (nome, codigo, id_area) values ('Vahlen-852', 'VAH416', 119);
insert into gdoks_subareas (nome, codigo, id_area) values ('Reindahl-207', 'REI713', 110);
insert into gdoks_subareas (nome, codigo, id_area) values ('Monica-668', 'MON325', 143);
insert into gdoks_subareas (nome, codigo, id_area) values ('Garrison-762', 'GAR542', 89);
insert into gdoks_subareas (nome, codigo, id_area) values ('Maryland-968', 'MAR897', 176);
insert into gdoks_subareas (nome, codigo, id_area) values ('Ilene-252', 'ILE877', 70);
