insert into gdoks_areas (nome, codigo, id_projeto) values ('Pearson-639', 'PEA586', 30);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Doe Crossing-876', 'DOE954', 19);
insert into gdoks_areas (nome, codigo, id_projeto) values ('International-554', 'INT375', 35);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Hansons-495', 'HAN439', 42);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Burning Wood-842', 'BUR934', 12);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Fisk-697', 'FIS742', 40);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Beilfuss-155', 'BEI705', 40);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Kenwood-663', 'KEN864', 7);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Bellgrove-108', 'BEL257', 45);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Oxford-231', 'OXF886', 2);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Transport-754', 'TRA644', 28);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Buhler-280', 'BUH495', 5);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Bay-426', 'BAY145', 22);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Hollow Ridge-246', 'HOL704', 51);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Goodland-270', 'GOO327', 59);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Lighthouse Bay-738', 'LIG745', 26);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Helena-530', 'HEL593', 35);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Waubesa-137', 'WAU470', 24);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Vernon-412', 'VER115', 5);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Porter-883', 'POR758', 34);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Dapin-488', 'DAP266', 55);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Merchant-997', 'MER493', 24);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Bartillon-200', 'BAR292', 56);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Scofield-414', 'SCO517', 45);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Linden-254', 'LIN868', 46);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Sherman-369', 'SHE367', 45);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Ridgeview-555', 'RID590', 45);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Lighthouse Bay-223', 'LIG971', 19);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Logan-853', 'LOG572', 60);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Rutledge-921', 'RUT318', 37);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Killdeer-441', 'KIL228', 21);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Bonner-671', 'BON579', 42);
insert into gdoks_areas (nome, codigo, id_projeto) values ('New Castle-633', 'NEW686', 45);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Hermina-475', 'HER552', 13);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Saint Paul-724', 'SAI855', 22);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Bobwhite-310', 'BOB263', 35);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Dapin-284', 'DAP365', 23);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Kipling-688', 'KIP735', 54);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Northwestern-792', 'NOR130', 54);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Arizona-204', 'ARI995', 3);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Grayhawk-998', 'GRA259', 14);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Division-190', 'DIV880', 6);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Cherokee-125', 'CHE241', 42);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Drewry-897', 'DRE724', 49);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Oneill-345', 'ONE110', 4);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Arrowood-476', 'ARR446', 55);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Northfield-936', 'NOR205', 58);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Wayridge-236', 'WAY211', 49);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Moland-756', 'MOL571', 43);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Florence-493', 'FLO347', 51);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Carberry-280', 'CAR383', 57);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Continental-660', 'CON493', 55);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Melby-402', 'MEL711', 10);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Toban-471', 'TOB125', 26);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Portage-448', 'POR557', 54);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Pepper Wood-947', 'PEP521', 11);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Ludington-659', 'LUD442', 45);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Blaine-709', 'BLA621', 50);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Truax-759', 'TRU640', 50);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Loftsgordon-464', 'LOF643', 43);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Melody-885', 'MEL455', 35);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Hanover-881', 'HAN476', 13);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Stephen-753', 'STE673', 58);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Eggendart-419', 'EGG187', 23);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Ridgeview-632', 'RID727', 3);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Eggendart-212', 'EGG265', 30);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Towne-129', 'TOW496', 51);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Merchant-471', 'MER870', 53);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Superior-924', 'SUP584', 16);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Steensland-423', 'STE111', 26);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Mandrake-366', 'MAN163', 57);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Arapahoe-550', 'ARA477', 7);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Dayton-936', 'DAY256', 47);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Jay-263', 'JAY173', 31);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Huxley-682', 'HUX470', 40);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Vermont-695', 'VER203', 31);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Bobwhite-188', 'BOB317', 29);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Fallview-639', 'FAL512', 57);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Clemons-336', 'CLE798', 42);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Troy-762', 'TRO297', 22);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Morningstar-177', 'MOR360', 52);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Barnett-133', 'BAR720', 11);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Steensland-107', 'STE568', 27);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Autumn Leaf-205', 'AUT864', 60);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Raven-435', 'RAV671', 11);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Stoughton-553', 'STO596', 2);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Monument-334', 'MON890', 23);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Eagan-653', 'EAG529', 1);
insert into gdoks_areas (nome, codigo, id_projeto) values ('John Wall-398', 'JOH713', 6);
insert into gdoks_areas (nome, codigo, id_projeto) values ('6th-812', '6TH554', 48);
insert into gdoks_areas (nome, codigo, id_projeto) values ('3rd-391', '3RD476', 21);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Raven-357', 'RAV903', 3);
insert into gdoks_areas (nome, codigo, id_projeto) values ('7th-527', '7TH570', 54);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Esch-142', 'ESC587', 39);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Prairie Rose-673', 'PRA348', 16);
insert into gdoks_areas (nome, codigo, id_projeto) values ('South-137', 'SOU829', 4);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Farwell-264', 'FAR845', 30);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Hoepker-866', 'HOE502', 58);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Bayside-229', 'BAY731', 46);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Ludington-508', 'LUD449', 1);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Southridge-483', 'SOU214', 25);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Grayhawk-359', 'GRA275', 56);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Rockefeller-909', 'ROC468', 54);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Michigan-549', 'MIC290', 30);
insert into gdoks_areas (nome, codigo, id_projeto) values ('School-188', 'SCH612', 44);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Loomis-461', 'LOO665', 20);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Lighthouse Bay-903', 'LIG857', 3);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Sloan-140', 'SLO548', 59);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Oak-141', 'OAK135', 25);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Orin-886', 'ORI242', 17);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Vahlen-869', 'VAH644', 26);
insert into gdoks_areas (nome, codigo, id_projeto) values ('8th-669', '8TH581', 48);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Rusk-490', 'RUS328', 30);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Grasskamp-381', 'GRA677', 11);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Stuart-953', 'STU410', 14);
insert into gdoks_areas (nome, codigo, id_projeto) values ('International-897', 'INT564', 60);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Farragut-525', 'FAR426', 16);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Hagan-478', 'HAG977', 36);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Washington-572', 'WAS612', 60);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Carey-755', 'CAR997', 7);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Buell-401', 'BUE785', 58);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Holy Cross-926', 'HOL744', 20);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Westerfield-267', 'WES402', 9);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Nelson-654', 'NEL406', 12);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Autumn Leaf-209', 'AUT933', 59);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Westerfield-870', 'WES756', 7);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Gina-434', 'GIN934', 37);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Towne-380', 'TOW954', 37);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Basil-280', 'BAS691', 43);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Dennis-985', 'DEN329', 49);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Carpenter-673', 'CAR783', 50);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Farwell-861', 'FAR372', 2);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Prairie Rose-739', 'PRA504', 6);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Hansons-371', 'HAN267', 53);
insert into gdoks_areas (nome, codigo, id_projeto) values ('North-144', 'NOR174', 12);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Forest Run-948', 'FOR815', 40);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Bashford-932', 'BAS670', 10);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Randy-754', 'RAN268', 46);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Northview-305', 'NOR945', 43);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Bellgrove-908', 'BEL368', 36);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Express-638', 'EXP456', 50);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Hoffman-368', 'HOF902', 12);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Northwestern-573', 'NOR452', 42);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Nevada-660', 'NEV954', 18);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Manufacturers-318', 'MAN343', 49);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Stang-759', 'STA809', 3);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Vidon-326', 'VID450', 14);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Bunting-221', 'BUN345', 17);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Red Cloud-290', 'RED107', 21);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Karstens-620', 'KAR307', 59);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Holmberg-337', 'HOL458', 33);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Porter-402', 'POR459', 12);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Barby-407', 'BAR291', 27);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Vermont-199', 'VER349', 48);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Summit-888', 'SUM775', 14);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Troy-416', 'TRO306', 5);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Harper-668', 'HAR541', 48);
insert into gdoks_areas (nome, codigo, id_projeto) values ('West-146', 'WES150', 14);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Hauk-857', 'HAU888', 25);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Stephen-359', 'STE641', 25);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Huxley-246', 'HUX843', 16);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Westport-383', 'WES223', 39);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Caliangt-635', 'CAL594', 27);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Continental-906', 'CON625', 31);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Bunting-138', 'BUN792', 59);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Del Sol-243', 'DEL663', 2);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Heffernan-128', 'HEF814', 3);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Washington-752', 'WAS706', 22);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Golf View-494', 'GOL711', 2);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Veith-872', 'VEI638', 33);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Ridgeview-669', 'RID198', 12);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Tomscot-954', 'TOM772', 53);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Lighthouse Bay-163', 'LIG461', 9);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Oak-651', 'OAK813', 43);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Rusk-172', 'RUS629', 6);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Old Shore-998', 'OLD945', 17);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Maple-848', 'MAP663', 57);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Eliot-128', 'ELI316', 32);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Gerald-380', 'GER993', 56);
insert into gdoks_areas (nome, codigo, id_projeto) values ('Paget-396', 'PAG380', 29);
