<?php
	define('ACAO_LOGOU', 1);
	define('ACAO_ALTEROU_DADOS_PESSOAIS', 2);
	define('ACAO_ALTEROU_DADOS_DE_USUARIO', 3);
	define('ACAO_CRIOU_USUARIO',4);
	define('ACAO_ALTEROU_DISCIPLINA',5);
	define('ACAO_CRIOU_DISCIPLINA',6);
	define('ACAO_ALTEROU_SUBDISCIPLINA',7);
	define('ACAO_CRIOU_SUBDISCIPLINA',8);
	define('ACAO_REMOVEU_SUBDISCIPLINA',9);
	define('ACAO_ASSOCIOU_ESPECIALISTA',10);
	define('ACAO_DESASSOCIOU_ESPECIALISTA',11);
	define('ACAO_ASSOCIOU_VALIDADOR',12);
	define('ACAO_DESASSOCIOU_VALIDADOR',13);
?>